// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqlg10zW3dvhdo4gWw12isBSbABSwRkQY',
    appId: '1:567938015187:android:1dbfff3513ae15e18e1926',
    messagingSenderId: '567938015187',
    projectId: 'solution-challange-e9810',
    storageBucket: 'solution-challange-e9810.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-WXkJiF9-0v31leAI2v1hTl42Nue5e4A',
    appId: '1:567938015187:ios:9d33083c05d1a0568e1926',
    messagingSenderId: '567938015187',
    projectId: 'solution-challange-e9810',
    storageBucket: 'solution-challange-e9810.appspot.com',
    androidClientId: '567938015187-6tbvtvp6qbma2bni6464tnio4j1kaom7.apps.googleusercontent.com',
    iosClientId: '567938015187-c223pfqi5mh6a4a9mac5sepi60728u0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodShare',
  );
}
